services:
  postgres:
    image: postgres:16-alpine
    container_name: shop-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  migration:
    build:
      context: ./
      dockerfile: internal/migrations/Dockerfile
    container_name: migration-runner
    env_file:
      - .env
    environment:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: "host=postgres port=${DB_PORT} user=${DB_USER} password=${DB_PASSWORD} dbname=${DB_NAME} sslmode=disable"
      GOOSE_MIGRATION_DIR: /app/migrations
    command:
      - sh
      - -c
      - |
        goose up
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"

  api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: shop-api
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: ${DB_PORT}
      SERVER_PORT: ${SERVER_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    restart: unless-stopped

volumes:
  postgres-data: